import { ConstructionItem } from './interface'

const constructionItems: ConstructionItem[] = [
  {
    id: 1,
    name: 'Item 1',
    src: '/recentJobs_1.png',
    alt: 'Alt text for Item 1',
    title: 'Title of Item 1',
    description: 'Description of Item 1',
  },
  {
    id: 2,
    name: 'Item 2',
    src: '/recentJobs_2.png',
    alt: 'Alt text for Item 2',
    title: 'Title of Item 2',
    description: 'Description of Item 2',
  },
  {
    id: 3,
    name: 'Item 3',
    src: '/recentJobs_3.png',
    alt: 'Alt text for Item 3',
    title: 'Title of Item 3',
    description: 'Description of Item 3',
  },
  {
    id: 4,
    name: 'Item 4',
    src: '/recentJobs_4.png',
    alt: 'Alt text for Item 4',
    title: 'Title of Item 4',
    description: 'Description of Item 4',
  },
  {
    id: 5,
    name: 'Item 5',
    src: '/recentJobs_5.png',
    alt: 'Alt text for Item 5',
    title: 'Title of Item 5',
    description: 'Description of Item 5',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
]

export default constructionItems
