import { ConstructionItem } from './interface'

const constructionItems: ConstructionItem[] = [
  {
    id: 1,
    name: 'Guarda-Corpo Metálico Ornamental para Escadas',
    src: '/recentJobs_1.png',
    alt: 'Guarda-Corpo Metálico Ornamental para Escadas',
    title: 'Guarda-Corpo Metálico Ornamental para Escadas',
    description:
      'Projetado exclusivamente para complementar escadas, este guarda-corpo oferece robustez e elegância na cor preta intensa, que contrasta perfeitamente com a leveza de escadas brancas. Os ornamentos cuidadosamente desenhados adicionam um toque de sofisticação, transformando um elemento de segurança em uma peça de arte decorativa. Ideal para ambientes residenciais ou comerciais que buscam estilo sem comprometer a funcionalidade.',
  },
  {
    id: 2,
    name: 'Guarda-Corpo Metálico Ornamental para Escadas',
    src: '/recentJobs_2.png',
    alt: 'Guarda-Corpo Metálico Ornamental para Escadas',
    title: 'Guarda-Corpo Metálico Ornamental para Escadas',
    description:
      'Projetado exclusivamente para complementar escadas, este guarda-corpo oferece robustez e elegância na cor preta intensa, que contrasta perfeitamente com a leveza de escadas brancas. Os ornamentos cuidadosamente desenhados adicionam um toque de sofisticação, transformando um elemento de segurança em uma peça de arte decorativa. Ideal para ambientes residenciais ou comerciais que buscam estilo sem comprometer a funcionalidade.',
  },
  {
    id: 3,
    name: 'Item 3',
    src: '/recentJobs_3.png',
    alt: 'Guarda-Corpo Metálico com Tela Integrada',
    title: 'Guarda-Corpo Metálico com Tela Integrada',
    description:
      'Guarda-Corpo Metálico com Tela Metálica Integrada é a escolha perfeita para quem busca proteção eficiente e estética contemporânea. Garantindo durabilidade e uma barreira segura contra quedas. A tela metálica oferece proteção sem obstruir a visão ou comprometer a entrada de luz natural, perfeita para ambientes que valorizam a transparência visual.',
  },
  {
    id: 4,
    name: 'Escada Metálica Helicoidal Pré-preparada para Revestimento',
    src: '/recentJobs_4.png',
    alt: 'Escada Metálica Helicoidal Pré-preparada para Revestimento',
    title: 'Escada Metálica Helicoidal Pré-preparada para Revestimento',
    description:
      'Projetada para ser o centro das atenções em qualquer ambiente. Esta estrutura espiralada não apenas economiza espaço, mas também é construída com materiais de alta qualidade que garantem durabilidade e estabilidade. O design inteligente da escada inclui uma preparação especial para revestimentos futuros, permitindo que você personalize a aparência para combinar com a evolução do seu estilo interior.',
  },
  {
    id: 5,
    name: 'Item 5',
    src: '/recentJobs_5.png',
    alt: 'Alt text for Item 5',
    title: 'Title of Item 5',
    description: 'Description of Item 5',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Maquises metalica com viga W e vidro',
    description: 'Description of Item 6',
  },
  {
    id: 7,
    name: 'Escada metalica em U com viga lateral e pisada em chapa de acao antiderrapante com guarda corpo atendendo normas do corpo de bombeiro',
    src: '/recentJobs_7.png',
    alt: 'Escada metalica em U com viga lateral e pisada em chapa de acao antiderrapante com guarda corpo atendendo normas do corpo de bombeiro',
    title:
      'Escada metalica em U com viga lateral e pisada em chapa de acao antiderrapante com guarda corpo atendendo normas do corpo de bombeiro',
    description: 'Description of Item 7',
  },
  {
    id: 8,
    name: 'Item 8',
    src: '/recentJobs_8.png',
    alt: 'Alt text for Item 8',
    title: 'Maquise metalica para receber vidro',
    description: 'Description of Item 8',
  },
  {
    id: 9,
    name: 'Item 9',
    src: '/recentJobs_9.png',
    alt: 'Alt text for Item 9',
    title: 'Guarda corpo metalico na sacada',
    description: 'Description of Item 9',
  },
  {
    id: 10,
    name: 'Item 10',
    src: '/recentJobs_10.png',
    alt: 'Alt text for Item 10',
    title: 'Title of Item 10',
    description: 'Description of Item 10',
  },
  {
    id: 11,
    name: 'Item 11',
    src: '/recentJobs_11.png',
    alt: 'Alt text for Item 11',
    title:
      'Escada metalica em L com viga lateral UDCe, pisada em chapa de aco antiderrapante com guarda corpo atendendo normas do corpo de bombeiro',
    description: 'Description of Item 11',
  },
  {
    id: 12,
    name: 'Item 12',
    src: '/recentJobs_12.png',
    alt: 'Alt text for Item 12',
    title: 'Title of Item 12',
    description: 'Description of Item 12',
  },
  {
    id: 13,
    name: 'Item 13',
    src: '/recentJobs_13.png',
    alt: 'Alt text for Item 13',
    title:
      'Escada metalica em U com viga lateral e chapa de aco antiderrapante com as normas do corpo de bombeiro',
    description: 'Description of Item 13',
  },
  {
    id: 14,
    name: 'Item 14',
    src: '/recentJobs_14.png',
    alt: 'Alt text for Item 14',
    title: 'Title of Item 14',
    description:
      'maquise metalica com viga w e perfil tubular para receber vidro',
  },
  {
    id: 15,
    name: 'Item 15',
    src: '/recentJobs_15.png',
    alt: 'Alt text for Item 15',
    title: 'Guarda corpo metalico',
    description: 'Description of Item 15',
  },
  {
    id: 16,
    name: 'Item 16',
    src: '/recentJobs_16.png',
    alt: 'Alt text for Item 16',
    title:
      'mezanino passarela tecnica escada marinheiro e guarda corpo metalico industrial',
    description: 'Description of Item 16',
  },
  {
    id: 17,
    name: 'Item 17',
    src: '/recentJobs_17.png',
    alt: 'Alt text for Item 17',
    title: 'Escada metalica revestida',
    description: 'Description of Item 17',
  },
  {
    id: 18,
    name: 'Item 18',
    src: '/recentJobs_18.png',
    alt: 'Alt text for Item 18',
    title:
      'reforco estrutural da residencia com viga W, VS e escada metalica com viga W central e pisadas com de aco grossa',
    description: 'Description of Item 18',
  },
  {
    id: 19,
    name: 'Item 19',
    src: '/recentJobs_19.png',
    alt: 'Alt text for Item 19',
    title:
      'reforco estrutural da residencia com viga W, VS e escada metalica com viga W central e pisadas com de aco grossa',
    description: 'Description of Item 19',
  },
  {
    id: 20,
    name: 'Item 20',
    src: '/recentJobs_20.png',
    alt: 'Alt text for Item 20',
    title:
      'reforco estrutural da residencia com viga W, VS e escada metalica com viga W central e pisadas com de aco grossa',
    description: 'Description of Item 20',
  },
  {
    id: 21,
    name: 'Item 21',
    src: '/recentJobs_21.png',
    alt: 'Alt text for Item 21',
    title: 'Painel metalico de teto decorativo',
    description: 'Description of Item 21',
  },
  {
    id: 22,
    name: 'Item 22',
    src: '/recentJobs_22.png',
    alt: 'Alt text for Item 22',
    title: 'Title of Item 22',
    description: 'Description of Item 22',
  },
  {
    id: 23,
    name: 'Item 23',
    src: '/recentJobs_23.png',
    alt: 'Alt text for Item 23',
    title: 'Title of Item 23',
    description: 'Description of Item 23',
  },
  {
    id: 24,
    name: 'Item 24',
    src: '/recentJobs_24.png',
    alt: 'Alt text for Item 24',
    title: 'Title of Item 24',
    description: 'Description of Item 24',
  },
  {
    id: 25,
    name: '25',
    src: '/recentJobs_25.png',
    alt: '25',
    title:
      'Escada metalica com viga central e chapa de aco lisa com revestimento em madeira',
    description: 'Description of Item 25',
  },
  {
    id: 26,
    name: 'Item 26',
    src: '/recentJobs_26.png',
    alt: 'Alt text for Item 26',
    title: 'Title of Item 26',
    description: 'Description of Item 26',
  },
  {
    id: 27,
    name: 'Item 27',
    src: '/recentJobs_27.png',
    alt: 'Alt text for Item 27',
    title:
      'Cobertura de garagem em balanco com tirantes rigidos e telha termo acustica',
    description: 'Description of Item 27',
  },
  {
    id: 28,
    name: 'Item 28',
    src: '/recentJobs_28.png',
    alt: 'Alt text for Item 28',
    title: 'Title of Item 28',
    description:
      'Cobertura de garagem com tirantes rigidos e telha termo acustica',
  },
  {
    id: 29,
    name: 'Item 29',
    src: '/recentJobs_29.png',
    alt: 'Alt text for Item 29',
    title: 'Title of Item 29',
    description: 'Description of Item 29',
  },
  {
    id: 30,
    name: 'Item 30',
    src: '/recentJobs_30.png',
    alt: 'Alt text for Item 30',
    title: 'Title of Item 30',
    description: 'Description of Item 30',
  },
  {
    id: 31,
    name: 'Item 31',
    src: '/recentJobs_31.png',
    alt: 'Alt text for Item 31',
    title:
      'Escada metalica com viga lateral laminada com bandeja para receber piso',
    description: 'Description of Item 31',
  },
  {
    id: 32,
    name: 'Item 32',
    src: '/recentJobs_32.png',
    alt: 'Alt text for Item 32',
    title: 'Guarda corpo metalico',
    description: 'Description of Item 32',
  },
  {
    id: 33,
    name: 'Item 33',
    src: '/recentJobs_33.png',
    alt: 'Alt text for Item 33',
    title: 'Passarela metalica com viga W e guarda corpo artistico',
    description: 'Description of Item 33',
  },
  {
    id: 34,
    name: 'Item 34',
    src: '/recentJobs_34.png',
    alt: 'Alt text for Item 34',
    title:
      'Escada metalica reta com viga UDC e pisada e espelho em chapa de aco antiderrapante',
    description:
      'Escada metalica reta com viga UDC e pisada e espelho em chapa de aco antiderrapante',
  },
  {
    id: 35,
    name: 'Item 35',
    src: '/recentJobs_35.png',
    alt: 'Alt text for Item 35',
    title: 'Title of Item 35',
    description: 'Description of Item 35',
  },
  {
    id: 36,
    name: 'Item 36',
    src: '/recentJobs_36.png',
    alt: 'Alt text for Item 36',
    title: 'Guarda corpo metalico',
    description: 'Description of Item 36',
  },
  {
    id: 37,
    name: 'Marquise metalica artistica dupla para receber vidro',
    src: '/recentJobs_37.png',
    alt: 'Marquise metalica artistica dupla para receber vidro',
    title: 'Marquise metalica artistica dupla para receber vidro',
    description: 'Description of Item 37',
  },
  {
    id: 38,
    name: 'Item 38',
    src: '/recentJobs_38.png',
    alt: 'Alt text for Item 38',
    title: 'Title of Item 38',
    description: 'Description of Item 38',
  },
  {
    id: 39,
    name: 'Item 39',
    src: '/recentJobs_39.png',
    alt: 'Alt text for Item 39',
    title: 'Marquise metalica artistica dupla para receber vidro',
    description: 'Description of Item 39',
  },
  {
    id: 40,
    name: 'Item 40',
    src: '/recentJobs_40.png',
    alt: 'Alt text for Item 40',
    title: 'Guarda corpo com ornatos artistico',
    description: 'Description of Item 40',
  },
  {
    id: 41,
    name: 'Item 41',
    src: '/recentJobs_41.png',
    alt: 'Alt text for Item 41',
    title: 'Mezanino com perfil tubular industrial e piso wall',
    description: 'Description of Item 41',
  },
  {
    id: 42,
    name: 'Item 42',
    src: '/recentJobs_42.png',
    alt: 'Alt text for Item 42',
    title: 'Guarda corpo em sacada preto',
    description: 'Description of Item 42',
  },
  {
    id: 43,
    name: 'Item 43',
    src: '/recentJobs_43.png',
    alt: 'Alt text for Item 43',
    title: 'Floreira calandra com chapa de aco galvanizada',
    description: 'Description of Item 43',
  },
]

export default constructionItems
