import { ConstructionItem } from './interface'

const constructionItems: ConstructionItem[] = [
  {
    id: 1,
    name: 'Item 1',
    src: '/recentJobs_1.png',
    alt: 'Alt text for Item 1',
    title: 'Title of Item 1',
    description: 'Description of Item 1',
  },
  {
    id: 2,
    name: 'Item 2',
    src: '/recentJobs_2.png',
    alt: 'Alt text for Item 2',
    title: 'Title of Item 2',
    description: 'Description of Item 2',
  },
  {
    id: 3,
    name: 'Item 3',
    src: '/recentJobs_3.png',
    alt: 'Alt text for Item 3',
    title: 'Title of Item 3',
    description: 'Description of Item 3',
  },
  {
    id: 4,
    name: 'Item 4',
    src: '/recentJobs_4.png',
    alt: 'Alt text for Item 4',
    title: 'Title of Item 4',
    description: 'Description of Item 4',
  },
  {
    id: 5,
    name: 'Item 5',
    src: '/recentJobs_5.png',
    alt: 'Alt text for Item 5',
    title: 'Title of Item 5',
    description: 'Description of Item 5',
  },
  {
    id: 6,
    name: 'Item 6',
    src: '/recentJobs_6.png',
    alt: 'Alt text for Item 6',
    title: 'Title of Item 6',
    description: 'Description of Item 6',
  },
  {
    id: 7,
    name: 'Item 7',
    src: '/recentJobs_7.png',
    alt: 'Alt text for Item 7',
    title: 'Title of Item 7',
    description: 'Description of Item 7',
  },
  {
    id: 8,
    name: 'Item 8',
    src: '/recentJobs_8.png',
    alt: 'Alt text for Item 8',
    title: 'Title of Item 8',
    description: 'Description of Item 8',
  },
  {
    id: 9,
    name: 'Item 9',
    src: '/recentJobs_9.png',
    alt: 'Alt text for Item 9',
    title: 'Title of Item 9',
    description: 'Description of Item 9',
  },
  {
    id: 10,
    name: 'Item 10',
    src: '/recentJobs_10.png',
    alt: 'Alt text for Item 10',
    title: 'Title of Item 10',
    description: 'Description of Item 10',
  },
  {
    id: 11,
    name: 'Item 11',
    src: '/recentJobs_11.png',
    alt: 'Alt text for Item 11',
    title: 'Title of Item 11',
    description: 'Description of Item 11',
  },
  {
    id: 12,
    name: 'Item 12',
    src: '/recentJobs_12.png',
    alt: 'Alt text for Item 12',
    title: 'Title of Item 12',
    description: 'Description of Item 12',
  },
  {
    id: 13,
    name: 'Item 13',
    src: '/recentJobs_13.png',
    alt: 'Alt text for Item 13',
    title: 'Title of Item 13',
    description: 'Description of Item 13',
  },
  {
    id: 14,
    name: 'Item 14',
    src: '/recentJobs_14.png',
    alt: 'Alt text for Item 14',
    title: 'Title of Item 14',
    description: 'Description of Item 14',
  },
  {
    id: 15,
    name: 'Item 15',
    src: '/recentJobs_15.png',
    alt: 'Alt text for Item 15',
    title: 'Title of Item 15',
    description: 'Description of Item 15',
  },
  {
    id: 16,
    name: 'Item 16',
    src: '/recentJobs_16.png',
    alt: 'Alt text for Item 16',
    title: 'Title of Item 16',
    description: 'Description of Item 16',
  },
  {
    id: 17,
    name: 'Item 17',
    src: '/recentJobs_17.png',
    alt: 'Alt text for Item 17',
    title: 'Title of Item 17',
    description: 'Description of Item 17',
  },
  {
    id: 18,
    name: 'Item 18',
    src: '/recentJobs_18.png',
    alt: 'Alt text for Item 18',
    title: 'Title of Item 18',
    description: 'Description of Item 18',
  },
  {
    id: 19,
    name: 'Item 19',
    src: '/recentJobs_19.png',
    alt: 'Alt text for Item 19',
    title: 'Title of Item 19',
    description: 'Description of Item 19',
  },
  {
    id: 20,
    name: 'Item 20',
    src: '/recentJobs_20.png',
    alt: 'Alt text for Item 20',
    title: 'Title of Item 20',
    description: 'Description of Item 20',
  },
  {
    id: 21,
    name: 'Item 21',
    src: '/recentJobs_21.png',
    alt: 'Alt text for Item 21',
    title: 'Title of Item 21',
    description: 'Description of Item 21',
  },
  {
    id: 22,
    name: 'Item 22',
    src: '/recentJobs_22.png',
    alt: 'Alt text for Item 22',
    title: 'Title of Item 22',
    description: 'Description of Item 22',
  },
  {
    id: 23,
    name: 'Item 23',
    src: '/recentJobs_23.png',
    alt: 'Alt text for Item 23',
    title: 'Title of Item 23',
    description: 'Description of Item 23',
  },
  {
    id: 24,
    name: 'Item 24',
    src: '/recentJobs_24.png',
    alt: 'Alt text for Item 24',
    title: 'Title of Item 24',
    description: 'Description of Item 24',
  },
  {
    id: 25,
    name: 'Item 25',
    src: '/recentJobs_25.png',
    alt: 'Alt text for Item 25',
    title: 'Title of Item 25',
    description: 'Description of Item 25',
  },
  {
    id: 26,
    name: 'Item 26',
    src: '/recentJobs_26.png',
    alt: 'Alt text for Item 26',
    title: 'Title of Item 26',
    description: 'Description of Item 26',
  },
  {
    id: 27,
    name: 'Item 27',
    src: '/recentJobs_27.png',
    alt: 'Alt text for Item 27',
    title: 'Title of Item 27',
    description: 'Description of Item 27',
  },
  {
    id: 28,
    name: 'Item 28',
    src: '/recentJobs_28.png',
    alt: 'Alt text for Item 28',
    title: 'Title of Item 28',
    description: 'Description of Item 28',
  },
  {
    id: 29,
    name: 'Item 29',
    src: '/recentJobs_29.png',
    alt: 'Alt text for Item 29',
    title: 'Title of Item 29',
    description: 'Description of Item 29',
  },
  {
    id: 30,
    name: 'Item 30',
    src: '/recentJobs_30.png',
    alt: 'Alt text for Item 30',
    title: 'Title of Item 30',
    description: 'Description of Item 30',
  },
  {
    id: 31,
    name: 'Item 31',
    src: '/recentJobs_31.png',
    alt: 'Alt text for Item 31',
    title: 'Title of Item 31',
    description: 'Description of Item 31',
  },
  {
    id: 32,
    name: 'Item 32',
    src: '/recentJobs_32.png',
    alt: 'Alt text for Item 32',
    title: 'Title of Item 32',
    description: 'Description of Item 32',
  },
  {
    id: 33,
    name: 'Item 33',
    src: '/recentJobs_33.png',
    alt: 'Alt text for Item 33',
    title: 'Title of Item 33',
    description: 'Description of Item 33',
  },
  {
    id: 34,
    name: 'Item 34',
    src: '/recentJobs_34.png',
    alt: 'Alt text for Item 34',
    title: 'Title of Item 34',
    description: 'Description of Item 34',
  },
  {
    id: 35,
    name: 'Item 35',
    src: '/recentJobs_35.png',
    alt: 'Alt text for Item 35',
    title: 'Title of Item 35',
    description: 'Description of Item 35',
  },
  {
    id: 36,
    name: 'Item 36',
    src: '/recentJobs_36.png',
    alt: 'Alt text for Item 36',
    title: 'Title of Item 36',
    description: 'Description of Item 36',
  },
  {
    id: 37,
    name: 'Item 37',
    src: '/recentJobs_37.png',
    alt: 'Alt text for Item 37',
    title: 'Title of Item 37',
    description: 'Description of Item 37',
  },
  {
    id: 38,
    name: 'Item 38',
    src: '/recentJobs_38.png',
    alt: 'Alt text for Item 38',
    title: 'Title of Item 38',
    description: 'Description of Item 38',
  },
  {
    id: 39,
    name: 'Item 39',
    src: '/recentJobs_39.png',
    alt: 'Alt text for Item 39',
    title: 'Title of Item 39',
    description: 'Description of Item 39',
  },
  {
    id: 40,
    name: 'Item 40',
    src: '/recentJobs_40.png',
    alt: 'Alt text for Item 40',
    title: 'Title of Item 40',
    description: 'Description of Item 40',
  },
  {
    id: 41,
    name: 'Item 41',
    src: '/recentJobs_41.png',
    alt: 'Alt text for Item 41',
    title: 'Title of Item 41',
    description: 'Description of Item 41',
  },
  {
    id: 42,
    name: 'Item 42',
    src: '/recentJobs_42.png',
    alt: 'Alt text for Item 42',
    title: 'Title of Item 42',
    description: 'Description of Item 42',
  },
  {
    id: 43,
    name: 'Item 43',
    src: '/recentJobs_43.png',
    alt: 'Alt text for Item 43',
    title: 'Title of Item 43',
    description: 'Description of Item 43',
  },
]

export default constructionItems
